GET http://127.0.0.1:8080/api/bids/storages HTTP/1.1

###

GET http://127.0.0.1:8080/api/bids/storages/1 HTTP/1.1

###

GET http://127.0.0.1:8080/api/bids/storages/1/datasets HTTP/1.1

###

GET http://127.0.0.1:8080/api/bids/storages/1/datasets/ds005616/files HTTP/1.1

###

POST http://127.0.0.1:8080/api/bids/openneuro/ds005625/collections HTTP/1.1

###

GET http://127.0.0.1:8080/api/bids/openneuro/datasets HTTP/1.1