@baseUrl = http://127.0.0.1:8080
# @baseUrl = http://workstation.home:18080
# @baseUrl = https://api.kp45.icu

GET {{baseUrl}}/api/storages HTTP/1.1

###

GET {{baseUrl}}/api/storages/1 HTTP/1.1

###

GET {{baseUrl}}/api/storages/1/status HTTP/1.1

###

PUT {{baseUrl}}/api/storages/1/bids HTTP/1.1

###

PUT {{baseUrl}}/api/storages/1/datasets HTTP/1.1

###

GET {{baseUrl}}/api/storages/1/datasets HTTP/1.1

###

GET {{baseUrl}}/api/datasets/1 HTTP/1.1

###

GET {{baseUrl}}/api/datasets/1/descriptions HTTP/1.1

###

GET {{baseUrl}}/api/datasets/1/files HTTP/1.1

###

POST {{baseUrl}}/api/openneuro/ds000108/collections?storageId=1 HTTP/1.1

###

GET {{baseUrl}}/api/openneuro/bids HTTP/1.1

###

GET {{baseUrl}}/api/bids-apps HTTP/1.1

###

PUT {{baseUrl}}/api/pipelines/collections HTTP/1.1

###

GET {{baseUrl}}/api/pipelines HTTP/1.1

###

GET {{baseUrl}}/api/pipelines/1 HTTP/1.1

###

POST {{baseUrl}}/api/jobs?name=test&group=test&pipelineId=57&datasetId=2 HTTP/1.1

###

GET {{baseUrl}}/api/jobs HTTP/1.1

###

GET {{baseUrl}}/api/jobs/1 HTTP/1.1

###

POST {{baseUrl}}/api/jobs/1/scheduling HTTP/1.1

###

GET {{baseUrl}}/api/jobs/1/artifacts HTTP/1.1

###

PUT {{baseUrl}}/api/jobs/1/artifacts HTTP/1.1

###

POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "test3@163.com",
  "password": "123456"
}

###

POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
  "username": "test3@163.com",
  "password": "123456"
}

###

POST {{baseUrl}}/api/collections/datasets/tasks?provider=CCNDC HTTP/1.1
Content-Type: application/json