version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - /data/local-stack/mysql:/var/lib/mysql
    restart: "unless-stopped"
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: "unless-stopped"
  kafka:
    container_name: kafka
    image: apache/kafka:3.9.0
    ports:
      - 9092:9092
    volumes:
      - /data/local-stack/kafka:/var/lib/kafka/data
    restart: "unless-stopped"
  vault:
    container_name: vault
    image: hashicorp/vault
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    volumes:
      - /data/local-stack/vault/config:/vault/config.d
    restart: "unless-stopped"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - "/data/local-stack/minio/data:/data"
    command: server /data --console-address ":9001"
    restart: "unless-stopped"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    command: start-dev
    depends_on:
      - mysql
    restart: "unless-stopped"
  bids-bridge-api:
    container_name: bids-bridge-api
    image: ghcr.io/kp45-tech/bids-bridge/bids-bridge:latest
    ports:
      - 8080:8080
    restart: "unless-stopped"