apiVersion: apps/v1
kind: Deployment
metadata:
  name: bids-bridge-redis
spec:
  selector:
    matchLabels:
      app: bids-bridge-redis
  template:
    metadata:
      labels:
        app: bids-bridge-redis
    spec:
      containers:
        - name: bids-bridge-redis
          image: redis
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: REDIS_PASSWORD
              value: password
          ports:
            - containerPort: 6379
