spring:
  application:
    name: bids-bridge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/bids_bridge?useUnicode=true&characterEncoding=utf-8&useSSL=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers:
      - ${KAFKA_SERVER}
    producer:
      # at least one replica has written the data to its log, if singletons broker set acks=1
      acks: all
      retries: 3
    consumer:
      fetch-min-size: 10
      auto-offset-reset: latest
      enable-auto-commit: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

job:
  engine:
    argo:
      serverUrl: https://localhost:2746
      namespace: argo
      token: 

bids:
  collector:
    openneuro:
      sync:
        enabled: false
        cron: 0 0 0 * * MON
        # cron: 0 0/1 * * * ?