spring:
  application:
    name: bids-bridge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/bids_bridge?useUnicode=true&characterEncoding=utf-8&useSSL=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers:
      - ${KAFKA_SERVER}

management:
  endpoints:
    web:
      exposure:
        include: "*"

bids:
  collector:
    openneuro:
      sync:
        cron: 0 0 0 * * MON
        # cron: 0 0/1 * * * ?
  storages:
    - id: 1
      name: default
      provider: MinioBidsStorageDal
      endpoint: ${MINIO_ENDPOINT}
      bucket: bids
      region: us-east-1
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      prefix: