spring:
  application:
    name: bids-bridge
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bids_bridge?useUnicode=true&characterEncoding=utf-8&useSSL=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: "*"

job:
  engine:
    argo:
      serverUrl: ${ARGO_WORKFLOW_SERVER:https://localhost:2746}
      namespace: argo
      token: 

bids:
  collector:
    openneuro:
      sync:
        enabled: true
        cron: 0 0 0 * * MON
        # cron: 0 0/5 * * * ?
      track:
        enabled: false
        cron: 0 0 0 * * MON
        # cron: 0 0/5 * * * ?