apiVersion: apps/v1
kind: Deployment
metadata:
  name: bids-bridge-api
spec:
  selector:
    matchLabels:
      app: bids-bridge-api
  template:
    metadata:
      labels:
        app: bids-bridge-api
    spec:
      containers:
        - name: bids-bridge-api
          image: ghcr.io/kevinpan45/bids-bridge:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
