apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: openneuro-collector
  namespace: argo
  generateName: openneuro-collector-
spec:
  entrypoint: rclone
  arguments:
    parameters:
    - name: dataset
      description: Accession number of the dataset
  # Automatic cleanup configuration
  ttlStrategy:
    secondsAfterCompletion: 1800  # Clean up 30 minutes after completion
    secondsAfterSuccess: 900      # Clean up 15 minutes after success
    secondsAfterFailure: 3600     # Clean up 1 hour after failure
  templates:
    - name: rclone
      inputs:
        parameters:
        - name: dataset
      container:
        image: rclone/rclone:latest
        command: ["rclone"]
        args:
          - "sync"
          - "s3:openneuro.org/{{workflow.parameters.dataset}}"
          - "minio:bids/{{workflow.parameters.dataset}}"
          - "--verbose"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
          - name: rclone-config
            mountPath: /root/.config/rclone/
            readOnly: true
      volumes:
        - name: rclone-config
          configMap:
            name: rclone-config