apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bids-apps-mriqc
  namespace: argo
  generateName: bids-apps-mriqc-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: dataset
      description: "BIDS dataset identifier"
  volumeClaimGC:
    strategy: OnWorkflowCompletion  # Keep workflow records but release storage after job completion
  volumeClaimTemplates:
  - metadata:
      name: shared-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  templates:
    - name: main
      steps:
        - - name: load-bids
            template: load-bids
            arguments:
              parameters:
              - name: dataset
                value: "{{workflow.parameters.dataset}}"
        - - name: execute-pipeline
            template: execute-pipeline
        - - name: upload-artifact
            template: upload-artifact
    - name: load-bids
      container:
        image: rclone/rclone:latest
        command: ["rclone"]
        args:
          - "copy"
          - "minio:bids/{{workflow.parameters.dataset}}"
          - "/shared/dataset"
          - "--verbose"
        volumeMounts:
          - name: rclone-config
            mountPath: /root/.config/rclone/
            readOnly: true
          - name: shared-data
            mountPath: /shared
      volumes:
        - name: rclone-config
          configMap:
            name: rclone-config
    - name: execute-pipeline
      container:
        image: nipreps/mriqc:24.0.2
        command: ["mriqc"]
        args: 
          - "/shared/dataset"
          - "/shared/artifact"
          - "participant"
        resources:
          requests:
            cpu: "8"
            memory: "32Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
        volumeMounts:
          - name: shared-data
            mountPath: /shared
    - name: upload-artifact
      container:
        image: rclone/rclone:latest
        command: ["rclone"]
        args:
          - "copy"
          - "/shared/artifact"
          - "minio:artifact/{{workflow.name}}"
          - "--verbose"
        volumeMounts:
          - name: rclone-config
            mountPath: /root/.config/rclone/
            readOnly: true
          - name: shared-data
            mountPath: /shared
      volumes:
        - name: rclone-config
          configMap:
            name: rclone-config