query advancedSearchDatasets($query: JSON!, $cursor: String, $allDatasets: Boolean, $datasetType: String, $datasetStatus: String, $sortBy: JSON) {
  datasets: advancedSearch(
    query: $query
    allDatasets: $allDatasets
    datasetType: $datasetType
    datasetStatus: $datasetStatus
    sortBy: $sortBy
    first: 25
    after: $cursor
  ) {
    edges {
      id
      node {
        id
        created
        uploader {
          id
          name
          orcid
          __typename
        }
        public
        permissions {
          id
          userPermissions {
            userId
            level
            access: level
            user {
              id
              name
              email
              provider
              __typename
            }
            __typename
          }
          __typename
        }
        metadata {
          ages
          __typename
        }
        latestSnapshot {
          size
          summary {
            modalities
            secondaryModalities
            sessions
            subjects
            subjectMetadata {
              participantId
              age
              sex
              group
              __typename
            }
            tasks
            size
            totalFiles
            dataProcessed
            pet {
              BodyPart
              ScannerManufacturer
              ScannerManufacturersModelName
              TracerName
              TracerRadionuclide
              __typename
            }
            __typename
          }
          issues {
            severity
            __typename
          }
          description {
            Name
            Authors
            __typename
          }
          __typename
        }
        analytics {
          views
          downloads
          __typename
        }
        stars {
          userId
          datasetId
          __typename
        }
        followers {
          userId
          datasetId
          __typename
        }
        snapshots {
          id
          created
          tag
          __typename
        }
        __typename
      }
      __typename
    }
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
      count
      __typename
    }
    __typename
  }
}
--------------------------------------------------
{
  "query": {
    "bool": {
      "filter": [
        {
          "match": {
            "latestSnapshot.summary.modalities": {
              "query": "MRI"
            }
          }
        }
      ]
    }
  },
  "sortBy": null,
  "datasetType": "All Public",
  "datasetStatus": null,
  "cursor": "WzAsImRzMDA1NTgxIl0="
}